id: PDD02E87C
initial_creation_type: input
source_metadata:
  title: Third Karmapa Series
  language: pt
  description: 'Texts by and about the Third Karmapa, Rangjung Dorje (karma pa rang
    byung rdo rje, 1284–1339):'
  volume:
    fdf8cd5b0d3c4dfbb392726e795d870f:
      title: Aspiration of the Mahāmudrā of Definitive Meaning
      parent: Aspiration Prayers
created_at: '2022-03-01T01:47:35.690292'
last_modified_at: '2022-03-01T01:47:35.690294'
